# .github/workflows/coverage.yml

# Workflow name
name: Code Coverage Summary Report

# Event for the workflow
on: push

# List of jobs
jobs:
  cobertura:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Run Storybook test coverages
      run: npx nyc report --reporter=cobertura -t coverage/storybook --report-dir .
    - name: Cover
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ./cobertura-coverage.xml
        badge: true
        fail_below_min: true