name: Testing pipeline
on:
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  call-playwright:
    uses: ./.github/workflows/playwright.yml
  call-chromatic:
    needs: call-playwright
    uses: ./.github/workflows/chromatic.yml
    with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}