# .github/workflows/vitest.yml

# Workflow name
name: 'vitest'

# Event for the workflow
on: push

# List of jobs
jobs:
  vitest-unit-test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: npm ci 
        # 👇 Adds vitest as a step in the workflow
      - name: Run unit tests
        run: npm run test:unit:run